version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "./inicio.sh &&
<<<<<<< HEAD
      python manage.py makemigrations login roles canvan publicaciones administracion cms &&
=======
      python manage.py makemigrations login cms roles canvan publicaciones administracion &&
>>>>>>> imagenes
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "8080:8080"    
