version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "./inicio.sh && unzip -o credencial.zip && python manage.py makemigrations comentarios roles login kanban administracion publicaciones && python manage.py migrate && python poblacion/poblar.py && gunicorn cms.wsgi:application --bind 0.0.0.0:8000 --limit-request-field_size 0"
    volumes:
      - .:/app

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - web
  
  localtunnel:
    image: defunctzombie/localtunnel-server
    command: --port 8080 --domain cms-is2-produccion.loca.lt
    network_mode: host
    restart: always
