version: '3.8'

services:
  db:
    image: postgres:14.9
    environment:
      POSTGRES_DB: cms_bd
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5434:5432"

  comodin:
    image: postgres:14.9
    environment:
      POSTGRES_DB: comodin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5435:5433"      
    depends_on:
      - db    

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "./inicio.sh && unzip -o credencial.zip
      && python manage.py makemigrations roles login kanban administracion publicaciones
      && python manage.py migrate
      && python poblacion/poblar.py
      && gunicorn cms.wsgi:application --bind 0.0.0.0:8000"  
    volumes:
      - .:/app
    depends_on:
      - comodin

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - web

